sudo: false

language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-supportsys
    - sys-img-armeabi-v7a-android-25
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

script: ./gradlew testDebug
